AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: demo for AWS Lambda development at local
Resources:
  FunctionName:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: put
      Timeout: 10
      Environment:
        Variables:
          #set variables in env.json file
          SAMPLE_KEY : !Ref SAMPLE_KEY
